# Suggested data paths when using GPT-NeoX locally
{
  "train-data-paths": [
    "data-fim-512/adl/adl_text_document",
    "data-fim-512/botxt/botxt_text_document",
    "data-fim-512/cc/cc_text_document",
    "data-fim-512/danavis/danavis_text_document",
    "data-fim-512/dannet/dannet_text_document",
    "data-fim-512/depbank/depbank_text_document",
    "data-fim-512/elrc-emea/elrc-emea_text_document",
    "data-fim-512/ep/ep_text_document",
    "data-fim-512/eubookshop/eubookshop_text_document",
    "data-fim-512/ft/ft_text_document",
    "data-fim-512/gutenberg/gutenberg_text_document",
    "data-fim-512/hest/hest_text_document",
    "data-fim-512/jvj/jvj_text_document",
    "data-fim-512/kb/kb_text_document",
    "data-fim-512/korpus2000/korpus2000_text_document",
    "data-fim-512/naat/naat_text_document",
    "data-fim-512/opensub/opensub_text_document",
    "data-fim-512/relig/relig_text_document",
    "data-fim-512/retsinformationdk/retsinformationdk_text_document",
    "data-fim-512/retspraksis/retspraksis_text_document",
    "data-fim-512/skat/skat_text_document",
    "data-fim-512/spont/spont_text_document",
    "data-fim-512/synne/synne_text_document",
    "data-fim-512/tidsskrift/tidsskrift_text_document",
    "data-fim-512/tv2r/tv2r_text_document",
    "data-fim-512/wiki/wiki_text_document",
    "data-fim-512/wikibooks/wikibooks_text_document",
    "data-fim-512/wikisource/wikisource_text_document",
  ],

  "test-data-paths": [
    "data-fim-512/adl/adl_text_document",
    "data-fim-512/botxt/botxt_text_document",
    "data-fim-512/cc/cc_text_document",
    "data-fim-512/danavis/danavis_text_document",
    "data-fim-512/dannet/dannet_text_document",
    "data-fim-512/depbank/depbank_text_document",
    "data-fim-512/elrc-emea/elrc-emea_text_document",
    "data-fim-512/ep/ep_text_document",
    "data-fim-512/eubookshop/eubookshop_text_document",
    "data-fim-512/ft/ft_text_document",
    "data-fim-512/gutenberg/gutenberg_text_document",
    "data-fim-512/hest/hest_text_document",
    "data-fim-512/jvj/jvj_text_document",
    "data-fim-512/kb/kb_text_document",
    "data-fim-512/korpus2000/korpus2000_text_document",
    "data-fim-512/naat/naat_text_document",
    "data-fim-512/opensub/opensub_text_document",
    "data-fim-512/relig/relig_text_document",
    "data-fim-512/retsinformationdk/retsinformationdk_text_document",
    "data-fim-512/retspraksis/retspraksis_text_document",
    "data-fim-512/skat/skat_text_document",
    "data-fim-512/spont/spont_text_document",
    "data-fim-512/synne/synne_text_document",
    "data-fim-512/tidsskrift/tidsskrift_text_document",
    "data-fim-512/tv2r/tv2r_text_document",
    "data-fim-512/wiki/wiki_text_document",
    "data-fim-512/wikibooks/wikibooks_text_document",
    "data-fim-512/wikisource/wikisource_text_document",
  ],

  "valid-data-paths": [
    "data-fim-512/adl/adl_text_document",
    "data-fim-512/botxt/botxt_text_document",
    "data-fim-512/cc/cc_text_document",
    "data-fim-512/danavis/danavis_text_document",
    "data-fim-512/dannet/dannet_text_document",
    "data-fim-512/depbank/depbank_text_document",
    "data-fim-512/elrc-emea/elrc-emea_text_document",
    "data-fim-512/ep/ep_text_document",
    "data-fim-512/eubookshop/eubookshop_text_document",
    "data-fim-512/ft/ft_text_document",
    "data-fim-512/gutenberg/gutenberg_text_document",
    "data-fim-512/hest/hest_text_document",
    "data-fim-512/jvj/jvj_text_document",
    "data-fim-512/kb/kb_text_document",
    "data-fim-512/korpus2000/korpus2000_text_document",
    "data-fim-512/naat/naat_text_document",
    "data-fim-512/opensub/opensub_text_document",
    "data-fim-512/relig/relig_text_document",
    "data-fim-512/retsinformationdk/retsinformationdk_text_document",
    "data-fim-512/retspraksis/retspraksis_text_document",
    "data-fim-512/skat/skat_text_document",
    "data-fim-512/spont/spont_text_document",
    "data-fim-512/synne/synne_text_document",
    "data-fim-512/tidsskrift/tidsskrift_text_document",
    "data-fim-512/tv2r/tv2r_text_document",
    "data-fim-512/wiki/wiki_text_document",
    "data-fim-512/wikibooks/wikibooks_text_document",
    "data-fim-512/wikisource/wikisource_text_document",
  ],

  # or for weighted datasets:
  # "train-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "test-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "valid-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "train-data-weights": [1., 2.],
  # "test-data-weights": [2., 1.],
  # "valid-data-weights": [0.5, 0.4],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  "weight_by_num_documents": True,
  "weighted_sampler_alpha": 0.3,

  "tokenizer-type": "HFTokenizer",
  "vocab-file": "../corpora/tokenizer/tokenizer.json",
  "merge-file": "../corpora/tokenizer/merges.txt",

  "save": "checkpoints-fim-512",
  "load": "checkpoints-fim-512",
  "checkpoint_validation_with_forward_pass": True,

  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": False,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox"
}
