# Suggested data paths when using GPT-NeoX locally
{
  "train-data-paths": [
    "data-fim/adl/adl_text_document",
    "data-fim/botxt/botxt_text_document",
    "data-fim/cc/cc_text_document",
    "data-fim/danavis/danavis_text_document",
    "data-fim/dannet/dannet_text_document",
    "data-fim/depbank/depbank_text_document",
    "data-fim/elrc-emea/elrc-emea_text_document",
    "data-fim/ep/ep_text_document",
    "data-fim/eubookshop/eubookshop_text_document",
    "data-fim/ft/ft_text_document",
    "data-fim/gutenberg/gutenberg_text_document",
    "data-fim/hest/hest_text_document",
    "data-fim/jvj/jvj_text_document",
    "data-fim/kb/kb_text_document",
    "data-fim/korpus2000/korpus2000_text_document",
    "data-fim/naat/naat_text_document",
    "data-fim/opensub/opensub_text_document",
    "data-fim/relig/relig_text_document",
    "data-fim/retsinformationdk/retsinformationdk_text_document",
    "data-fim/retspraksis/retspraksis_text_document",
    "data-fim/skat/skat_text_document",
    "data-fim/spont/spont_text_document",
    "data-fim/synne/synne_text_document",
    "data-fim/tidsskrift/tidsskrift_text_document",
    "data-fim/tv2r/tv2r_text_document",
    "data-fim/wiki/wiki_text_document",
    "data-fim/wikibooks/wikibooks_text_document",
    "data-fim/wikisource/wikisource_text_document",
  ],

  "test-data-paths": [
    "data-fim/adl/adl_text_document",
    "data-fim/botxt/botxt_text_document",
    "data-fim/cc/cc_text_document",
    "data-fim/danavis/danavis_text_document",
    "data-fim/dannet/dannet_text_document",
    "data-fim/depbank/depbank_text_document",
    "data-fim/elrc-emea/elrc-emea_text_document",
    "data-fim/ep/ep_text_document",
    "data-fim/eubookshop/eubookshop_text_document",
    "data-fim/ft/ft_text_document",
    "data-fim/gutenberg/gutenberg_text_document",
    "data-fim/hest/hest_text_document",
    "data-fim/jvj/jvj_text_document",
    "data-fim/kb/kb_text_document",
    "data-fim/korpus2000/korpus2000_text_document",
    "data-fim/naat/naat_text_document",
    "data-fim/opensub/opensub_text_document",
    "data-fim/relig/relig_text_document",
    "data-fim/retsinformationdk/retsinformationdk_text_document",
    "data-fim/retspraksis/retspraksis_text_document",
    "data-fim/skat/skat_text_document",
    "data-fim/spont/spont_text_document",
    "data-fim/synne/synne_text_document",
    "data-fim/tidsskrift/tidsskrift_text_document",
    "data-fim/tv2r/tv2r_text_document",
    "data-fim/wiki/wiki_text_document",
    "data-fim/wikibooks/wikibooks_text_document",
    "data-fim/wikisource/wikisource_text_document",
  ],

  "valid-data-paths": [
    "data-fim/adl/adl_text_document",
    "data-fim/botxt/botxt_text_document",
    "data-fim/cc/cc_text_document",
    "data-fim/danavis/danavis_text_document",
    "data-fim/dannet/dannet_text_document",
    "data-fim/depbank/depbank_text_document",
    "data-fim/elrc-emea/elrc-emea_text_document",
    "data-fim/ep/ep_text_document",
    "data-fim/eubookshop/eubookshop_text_document",
    "data-fim/ft/ft_text_document",
    "data-fim/gutenberg/gutenberg_text_document",
    "data-fim/hest/hest_text_document",
    "data-fim/jvj/jvj_text_document",
    "data-fim/kb/kb_text_document",
    "data-fim/korpus2000/korpus2000_text_document",
    "data-fim/naat/naat_text_document",
    "data-fim/opensub/opensub_text_document",
    "data-fim/relig/relig_text_document",
    "data-fim/retsinformationdk/retsinformationdk_text_document",
    "data-fim/retspraksis/retspraksis_text_document",
    "data-fim/skat/skat_text_document",
    "data-fim/spont/spont_text_document",
    "data-fim/synne/synne_text_document",
    "data-fim/tidsskrift/tidsskrift_text_document",
    "data-fim/tv2r/tv2r_text_document",
    "data-fim/wiki/wiki_text_document",
    "data-fim/wikibooks/wikibooks_text_document",
    "data-fim/wikisource/wikisource_text_document",
  ],

  # or for weighted datasets:
  # "train-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "test-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "valid-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "train-data-weights": [1., 2.],
  # "test-data-weights": [2., 1.],
  # "valid-data-weights": [0.5, 0.4],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  "weight_by_num_documents": True,
  "weighted_sampler_alpha": 0.3,

  "tokenizer-type": "HFTokenizer",
  "vocab-file": "../corpora/tokenizer/tokenizer.json",
  "merge-file": "../corpora/tokenizer/merges.txt",

  "save": "checkpoints",
  "load": "checkpoints",
  "checkpoint_validation_with_forward_pass": True,

  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": False,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox"
}
