# Suggested data paths when using GPT-NeoX locally
{
  "train-data-paths": [
    "data-fcm/adl/adl_text_document",
    "data-fcm/botxt/botxt_text_document",
    "data-fcm/cc/cc_text_document",
    "data-fcm/danavis/danavis_text_document",
    "data-fcm/dannet/dannet_text_document",
    "data-fcm/depbank/depbank_text_document",
    "data-fcm/elrc-emea/elrc-emea_text_document",
    "data-fcm/ep/ep_text_document",
    "data-fcm/eubookshop/eubookshop_text_document",
    "data-fcm/ft/ft_text_document",
    "data-fcm/gutenberg/gutenberg_text_document",
    "data-fcm/hest/hest_text_document",
    "data-fcm/jvj/jvj_text_document",
    "data-fcm/kb/kb_text_document",
    "data-fcm/korpus2000/korpus2000_text_document",
    "data-fcm/naat/naat_text_document",
    "data-fcm/opensub/opensub_text_document",
    "data-fcm/relig/relig_text_document",
    "data-fcm/retsinformationdk/retsinformationdk_text_document",
    "data-fcm/retspraksis/retspraksis_text_document",
    "data-fcm/skat/skat_text_document",
    "data-fcm/spont/spont_text_document",
    "data-fcm/synne/synne_text_document",
    "data-fcm/tidsskrift/tidsskrift_text_document",
    "data-fcm/tv2r/tv2r_text_document",
    "data-fcm/wiki/wiki_text_document",
    "data-fcm/wikibooks/wikibooks_text_document",
    "data-fcm/wikisource/wikisource_text_document",
  ],

  "test-data-paths": [
    "data-fcm/adl/adl_text_document",
    "data-fcm/botxt/botxt_text_document",
    "data-fcm/cc/cc_text_document",
    "data-fcm/danavis/danavis_text_document",
    "data-fcm/dannet/dannet_text_document",
    "data-fcm/depbank/depbank_text_document",
    "data-fcm/elrc-emea/elrc-emea_text_document",
    "data-fcm/ep/ep_text_document",
    "data-fcm/eubookshop/eubookshop_text_document",
    "data-fcm/ft/ft_text_document",
    "data-fcm/gutenberg/gutenberg_text_document",
    "data-fcm/hest/hest_text_document",
    "data-fcm/jvj/jvj_text_document",
    "data-fcm/kb/kb_text_document",
    "data-fcm/korpus2000/korpus2000_text_document",
    "data-fcm/naat/naat_text_document",
    "data-fcm/opensub/opensub_text_document",
    "data-fcm/relig/relig_text_document",
    "data-fcm/retsinformationdk/retsinformationdk_text_document",
    "data-fcm/retspraksis/retspraksis_text_document",
    "data-fcm/skat/skat_text_document",
    "data-fcm/spont/spont_text_document",
    "data-fcm/synne/synne_text_document",
    "data-fcm/tidsskrift/tidsskrift_text_document",
    "data-fcm/tv2r/tv2r_text_document",
    "data-fcm/wiki/wiki_text_document",
    "data-fcm/wikibooks/wikibooks_text_document",
    "data-fcm/wikisource/wikisource_text_document",
  ],

  "valid-data-paths": [
    "data-fcm/adl/adl_text_document",
    "data-fcm/botxt/botxt_text_document",
    "data-fcm/cc/cc_text_document",
    "data-fcm/danavis/danavis_text_document",
    "data-fcm/dannet/dannet_text_document",
    "data-fcm/depbank/depbank_text_document",
    "data-fcm/elrc-emea/elrc-emea_text_document",
    "data-fcm/ep/ep_text_document",
    "data-fcm/eubookshop/eubookshop_text_document",
    "data-fcm/ft/ft_text_document",
    "data-fcm/gutenberg/gutenberg_text_document",
    "data-fcm/hest/hest_text_document",
    "data-fcm/jvj/jvj_text_document",
    "data-fcm/kb/kb_text_document",
    "data-fcm/korpus2000/korpus2000_text_document",
    "data-fcm/naat/naat_text_document",
    "data-fcm/opensub/opensub_text_document",
    "data-fcm/relig/relig_text_document",
    "data-fcm/retsinformationdk/retsinformationdk_text_document",
    "data-fcm/retspraksis/retspraksis_text_document",
    "data-fcm/skat/skat_text_document",
    "data-fcm/spont/spont_text_document",
    "data-fcm/synne/synne_text_document",
    "data-fcm/tidsskrift/tidsskrift_text_document",
    "data-fcm/tv2r/tv2r_text_document",
    "data-fcm/wiki/wiki_text_document",
    "data-fcm/wikibooks/wikibooks_text_document",
    "data-fcm/wikisource/wikisource_text_document",
  ],

  # or for weighted datasets:
  # "train-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "test-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "valid-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "train-data-weights": [1., 2.],
  # "test-data-weights": [2., 1.],
  # "valid-data-weights": [0.5, 0.4],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  "weight_by_num_documents": True,
  "weighted_sampler_alpha": 0.3,

  "tokenizer-type": "HFTokenizer",
  "vocab-file": "../corpora/tokenizer/tokenizer.json",
  "merge-file": "../corpora/tokenizer/merges.txt",

  "save": "checkpoints-fcm",
  "load": "checkpoints-fcm",
  "checkpoint_validation_with_forward_pass": True,

  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": False,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox"
}
