# Suggested data paths when using GPT-NeoX locally
{
  "train-data-paths": [
    "data-tfcm/adl/adl_text_document",
    "data-tfcm/botxt/botxt_text_document",
    "data-tfcm/cc/cc_text_document",
    "data-tfcm/danavis/danavis_text_document",
    "data-tfcm/dannet/dannet_text_document",
    "data-tfcm/depbank/depbank_text_document",
    "data-tfcm/elrc-emea/elrc-emea_text_document",
    "data-tfcm/ep/ep_text_document",
    "data-tfcm/eubookshop/eubookshop_text_document",
    "data-tfcm/ft/ft_text_document",
    "data-tfcm/gutenberg/gutenberg_text_document",
    "data-tfcm/hest/hest_text_document",
    "data-tfcm/jvj/jvj_text_document",
    "data-tfcm/kb/kb_text_document",
    "data-tfcm/korpus2000/korpus2000_text_document",
    "data-tfcm/naat/naat_text_document",
    "data-tfcm/opensub/opensub_text_document",
    "data-tfcm/relig/relig_text_document",
    "data-tfcm/retsinformationdk/retsinformationdk_text_document",
    "data-tfcm/retspraksis/retspraksis_text_document",
    "data-tfcm/skat/skat_text_document",
    "data-tfcm/spont/spont_text_document",
    "data-tfcm/synne/synne_text_document",
    "data-tfcm/tidsskrift/tidsskrift_text_document",
    "data-tfcm/tv2r/tv2r_text_document",
    "data-tfcm/wiki/wiki_text_document",
    "data-tfcm/wikibooks/wikibooks_text_document",
    "data-tfcm/wikisource/wikisource_text_document",
  ],

  "test-data-paths": [
    "data-tfcm/adl/adl_text_document",
    "data-tfcm/botxt/botxt_text_document",
    "data-tfcm/cc/cc_text_document",
    "data-tfcm/danavis/danavis_text_document",
    "data-tfcm/dannet/dannet_text_document",
    "data-tfcm/depbank/depbank_text_document",
    "data-tfcm/elrc-emea/elrc-emea_text_document",
    "data-tfcm/ep/ep_text_document",
    "data-tfcm/eubookshop/eubookshop_text_document",
    "data-tfcm/ft/ft_text_document",
    "data-tfcm/gutenberg/gutenberg_text_document",
    "data-tfcm/hest/hest_text_document",
    "data-tfcm/jvj/jvj_text_document",
    "data-tfcm/kb/kb_text_document",
    "data-tfcm/korpus2000/korpus2000_text_document",
    "data-tfcm/naat/naat_text_document",
    "data-tfcm/opensub/opensub_text_document",
    "data-tfcm/relig/relig_text_document",
    "data-tfcm/retsinformationdk/retsinformationdk_text_document",
    "data-tfcm/retspraksis/retspraksis_text_document",
    "data-tfcm/skat/skat_text_document",
    "data-tfcm/spont/spont_text_document",
    "data-tfcm/synne/synne_text_document",
    "data-tfcm/tidsskrift/tidsskrift_text_document",
    "data-tfcm/tv2r/tv2r_text_document",
    "data-tfcm/wiki/wiki_text_document",
    "data-tfcm/wikibooks/wikibooks_text_document",
    "data-tfcm/wikisource/wikisource_text_document",
  ],

  "valid-data-paths": [
    "data-tfcm/adl/adl_text_document",
    "data-tfcm/botxt/botxt_text_document",
    "data-tfcm/cc/cc_text_document",
    "data-tfcm/danavis/danavis_text_document",
    "data-tfcm/dannet/dannet_text_document",
    "data-tfcm/depbank/depbank_text_document",
    "data-tfcm/elrc-emea/elrc-emea_text_document",
    "data-tfcm/ep/ep_text_document",
    "data-tfcm/eubookshop/eubookshop_text_document",
    "data-tfcm/ft/ft_text_document",
    "data-tfcm/gutenberg/gutenberg_text_document",
    "data-tfcm/hest/hest_text_document",
    "data-tfcm/jvj/jvj_text_document",
    "data-tfcm/kb/kb_text_document",
    "data-tfcm/korpus2000/korpus2000_text_document",
    "data-tfcm/naat/naat_text_document",
    "data-tfcm/opensub/opensub_text_document",
    "data-tfcm/relig/relig_text_document",
    "data-tfcm/retsinformationdk/retsinformationdk_text_document",
    "data-tfcm/retspraksis/retspraksis_text_document",
    "data-tfcm/skat/skat_text_document",
    "data-tfcm/spont/spont_text_document",
    "data-tfcm/synne/synne_text_document",
    "data-tfcm/tidsskrift/tidsskrift_text_document",
    "data-tfcm/tv2r/tv2r_text_document",
    "data-tfcm/wiki/wiki_text_document",
    "data-tfcm/wikibooks/wikibooks_text_document",
    "data-tfcm/wikisource/wikisource_text_document",
  ],

  # or for weighted datasets:
  # "train-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "test-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "valid-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "train-data-weights": [1., 2.],
  # "test-data-weights": [2., 1.],
  # "valid-data-weights": [0.5, 0.4],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  "weight_by_num_documents": True,
  "weighted_sampler_alpha": 0.3,

  "tokenizer-type": "HFTokenizer",
  "vocab-file": "../corpora/tokenizer/tokenizer.json",
  "merge-file": "../corpora/tokenizer/merges.txt",

  "save": "checkpoints-tfcm",
  "load": "checkpoints-tfcm",
  "checkpoint_validation_with_forward_pass": True,

  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": False,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox"
}
